artifact_uri: file:///home/runner/work/Workflow-CI/Workflow-CI/mlruns/0/f786b81eaf334a498ab513fd5153ee24/artifacts
end_time: 1750248296548
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f786b81eaf334a498ab513fd5153ee24
run_name: omniscient-mare-499
source_name: ''
source_type: 4
source_version: ''
start_time: 1750248292195
status: 3
tags: []
user_id: runner
