name: Integrasi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/loan_preprocessing.csv"
  TARGET_VAR: "Loan_Approval"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      # Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow  
          
      # Run mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local 
      
      # Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # Github
      - name: Upload to GitHub
        run: |
          # Konfigurasi Git
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          
          # Buat branch baru atau gunakan yang sudah ada
          git checkout -b artifacts || git checkout artifacts
          
          # Buat folder terstruktur untuk run
          mkdir -p saved_runs/${{ env.RUN_ID }}
          
          # Salin hasil run
          cp -r mlruns/0/${{ env.RUN_ID }}/* saved_runs/${{ env.RUN_ID }}/
          
          # Tambahkan metadata
          echo "Run ID: ${{ env.RUN_ID }}" > saved_runs/${{ env.RUN_ID }}/metadata.txt
          echo "Date: $(date)" >> saved_runs/${{ env.RUN_ID }}/metadata.txt
          
          # Commit dan push
          git add saved_runs/
          git commit -m "Save artifacts from run ${{ env.RUN_ID }} [skip ci]"
          git push origin artifacts --force
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # Docker
      # Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "workflow" 

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag workflow ${{ secrets.DOCKER_HUB_USERNAME }}/workflow:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/workflow:latest
